"use client"

import Link from "next/link"
import Image from "next/image"
import { usePathname } from "next/navigation"
import {
  LayoutGrid,
  ShoppingBag,
  Tags,
  Image as ImageIcon,
  Truck,
  Users,
  BadgePercent,
  FileText,
  Settings,
  LogOut,
  BookOpen,
  Mail,
  Star,
} from "lucide-react"
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar"
import { Button } from "@/components/ui/button"
import { createClient } from "@/lib/supabase/client"
import { cn } from "@/lib/utils"

const NAV = [
  { href: "/admin/tableau", label: "Dashboard", icon: LayoutGrid },
  { href: "/admin/commandes", label: "Commandes", icon: Truck },
  { href: "/admin/produits", label: "Produits", icon: ShoppingBag },
  { href: "/admin/categories", label: "Catégories", icon: Tags },
  { href: "/admin/hero", label: "Hero", icon: ImageIcon },
  { href: "/admin/clients", label: "Clients", icon: Users },
  { href: "/admin/avis", label: "Avis", icon: Star },
  { href: "/admin/newsletter", label: "Newsletter", icon: Mail },
  { href: "/admin/promotions", label: "Promotions", icon: BadgePercent },
  { href: "/admin/contenu", label: "Contenu", icon: FileText },
  { href: "/admin/a-propos", label: "À propos", icon: BookOpen },
  { href: "/admin/parametres", label: "Paramètres", icon: Settings },
] as const

export function AdminShell({
  children,
  adminEmail,
}: {
  children: React.ReactNode
  adminEmail: string
}) {
  const pathname = usePathname()

  return (
    <SidebarProvider defaultOpen={true}>
      <Sidebar
        variant="sidebar"
        collapsible="icon"
        className={cn(
          // Container
          "text-[#2a2520]",
          // Target inner element generated by `components/ui/sidebar.tsx`
          "[&_[data-slot=sidebar-inner]]:bg-gradient-to-b [&_[data-slot=sidebar-inner]]:from-[#F7F3EC] [&_[data-slot=sidebar-inner]]:to-[#efe6d7]",
          "[&_[data-slot=sidebar-inner]]:shadow-[inset_-1px_0_0_rgba(0,0,0,0.06)]",
        )}
      >
        <SidebarHeader className="border-b border-black/10">
          <div className="flex items-center justify-between px-2 py-2">
            <Link href="/admin/tableau" className="flex items-center gap-2">
              <span className="relative h-7 w-7 overflow-hidden rounded-md border border-black/10 bg-[#F7F3EC]">
                <Image
                  src="/ms-logo-new.png"
                  alt=""
                  fill
                  className="object-contain p-0.5"
                  sizes="28px"
                  priority
                />
              </span>
              <span className="text-sm font-bold tracking-[0.22em] text-[#2a2520]">MBOULANE</span>
              <span className="text-xs font-semibold tracking-[0.28em] text-[#b38b6d]">ADMIN</span>
            </Link>
            <SidebarTrigger className="text-[#6b5d4f] hover:text-[#2a2520]" />
          </div>
        </SidebarHeader>

        <SidebarContent className="px-1 py-2">
          <SidebarMenu>
            {NAV.map((item) => {
              const active =
                pathname === item.href ||
                (item.href === "/admin/tableau" && pathname === "/admin")
              const Icon = item.icon
              return (
                <SidebarMenuItem key={item.href}>
                  <SidebarMenuButton
                    asChild
                    isActive={active}
                    tooltip={item.label}
                    className={cn(
                      "mx-1 rounded-[10px] text-[#6b5d4f] hover:bg-black/5 hover:text-[#2a2520]",
                      active && "bg-black/5 text-[#2a2520]",
                    )}
                  >
                    <Link href={item.href}>
                      <Icon />
                      <span>{item.label}</span>
                    </Link>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              )
            })}
          </SidebarMenu>
        </SidebarContent>

        <SidebarFooter className="border-t border-black/10">
          <div className="flex items-center justify-between gap-3 px-3 py-3">
            <div className="min-w-0">
              <p className="truncate text-xs font-semibold text-[#2a2520]">{adminEmail}</p>
              <p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#6b5d4f]">
                Administrateur
              </p>
            </div>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="rounded-full text-[#6b5d4f] hover:bg-black/5 hover:text-[#2a2520]"
              onClick={async () => {
                const supabase = createClient()
                await supabase.auth.signOut()
                window.location.href = "/admin/connexion"
              }}
              title="Déconnexion"
            >
              <LogOut className="h-4 w-4" />
            </Button>
          </div>
        </SidebarFooter>
      </Sidebar>

      <SidebarInset className="bg-[#0b0b0c]">
        <header className="sticky top-0 z-40 border-b border-black/10 bg-[#F7F3EC] backdrop-blur md:border-white/10 md:bg-[#0b0b0c]/85">
          <div className="relative mx-auto flex h-14 max-w-[1400px] items-center justify-between px-4 sm:px-6 lg:px-8">
            {/* Gauche (mobile) : bouton menu qui ouvre le drawer */}
            <div className="flex items-center gap-2">
              <SidebarTrigger className="text-[#2a2520] hover:text-black md:hidden" />
              <p className="hidden text-xs font-semibold uppercase tracking-[0.22em] text-white/50 md:block">
                Back‑office
              </p>
            </div>

            {/* Centre (mobile) : titre centré */}
            <div className="pointer-events-none absolute left-1/2 -translate-x-1/2 md:hidden">
              <div className="flex items-center gap-2">
                <span className="relative h-6 w-6 overflow-hidden rounded-md border border-black/10 bg-[#F7F3EC]">
                  <Image
                    src="/ms-logo-new.png"
                    alt=""
                    fill
                    className="object-contain p-0.5"
                    sizes="24px"
                    priority
                  />
                </span>
                <p className="text-xs font-bold uppercase tracking-[0.32em] text-[#2a2520]">
                  MBOULANE <span className="text-[#b38b6d]">ADMIN</span>
                </p>
              </div>
            </div>

            {/* Droite (desktop) */}
            <div className="flex items-center gap-2">
              <span className="hidden text-xs font-semibold text-white/50 md:inline">
                {adminEmail}
              </span>
            </div>
          </div>
        </header>

        <div className="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-8">
          {children}
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}

